version: "3.7"

services:
  valicare-php-cli:
    build:
      dockerfile: .docker/cli.Dockerfile
      context: ../
    working_dir: /app
    volumes:
      - ../.:/app:cached
    image: valicare-api-php-cli
    networks:
      - main

networks:
  main:
